const hike = [
  {
    id: 1,
    title: 'Clouds Rest',
    category: 'hard',
    about: '12 miles',
    img: './images/item-1.jpeg',
    desc: `Clouds Rest is a long trail that leads to some seriously stunning views. In fact, in my opinion, it’s probably the second-best hike in Yosemite! `,
  },
  {
    id: 2,
    title: 'Half Dome',
    category: 'hard',
    about: '16 miles',
    img: './images/item-2.jpeg',
    desc: `Half Dome is a serious endurance hike taking you 4800 feet above the Yosemite Valley to spectacular views of Vernal and Nevada Falls. `,
  },
  {
    id: 3,
    title: 'Glacier Point',
    category:'easy',
    about: '1 mile',
    img: './images/item-3.jpeg',
    desc: `There's a 270-degree panorama including Half Dome, Clouds Rest, the waterfalls of the Mist Trail, dozens of peaks in the eastern Sierra range, and much of Yosemite Valley. It's probably the best place in all of Yosemite for watching the sunset.`,
  },
  {
    id: 4,
    title: 'Tenaya Lake',
    category: 'easy',
    about: '2.5 miles',
    img: './images/item-4.jpeg',
    desc: `Hike this beautiful loop around the lake or enjoy a lazy day on its sandy shore (or do both!). It’s an excellent place to spend the day. `,
  },
  {
    id: 5,
    title: 'Upper Yosemite Falls Trail',
    category: 'hard',
    about: '7.6 miles',
    img: './images/item-5.jpeg',
    desc: `The Yosemite Falls hike is an epic-stair-master workout, but affords you some amazing views of the classic Yosemite Valley landmarks and scenery. `,
  },
  {
    id: 6,
    title: 'Lower Yosemite Falls',
    category: 'easy',
    about: '0.5 miles',
    img: './images/item-6.jpeg',
    desc: `If you spend any time at all in Yosemite Village, make sure to stop by to get an epic view up at Yosemite Falls.`,
  },
  {
    id: 7,
    title: 'Cathedral Lakes Trail',
    category: 'moderate',
    about: '8 miles',
    img: './images/item-7.jpeg',
    desc: `Relatively moderate hike into 2 stunning lakes with views of one of Tuolumne’s most iconic peaks, Cathedral Peak.`,
  },
  {
    id: 8,
    title: 'Mono Pass Trail',
    category: 'moderate',
    about: '7.4 miles',
    img: './images/item-8.jpeg',
    desc: `The Mono Pass trail is a relatively low key trail crowd wise when compared to the hikes in the heart of Yosemite Valley, and this trail offers unique views and landmarks outside the classic famous Yosemite Valley scenery.  `,
  },
  {
    id: 9,
    title: 'Elizabeth Lake Trail',
    category: 'moderate',
    about: '4.9 miles',
    img: './images/item-9.jpeg',
    desc: `The start of the hike to Elizabeth Lake is steep enough to keep away some of the crowds in Tuolumne, as it gains a lot of its elevation in the first mile. But if you make it through that uphill slog, you’ll find yourself crossing a lovely meadow on the way to the lake.`,
  },
];
export default hike;
